stages:
  - lint
  - test
  - end_to_end
matrix:
  include:
  - name: "Pylint on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    stage: lint
    env: [TARGET="pylint", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Fedora Core 30 (Docker) with Python 2.7"
    stage: test
    env: FEDORA_VERSION="30"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Fedora Core 30 (Docker) with Python 3.7"
    stage: test
    env: FEDORA_VERSION="30"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 2.7"
    stage: test
    env: [TARGET="coverage", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    stage: test
    env: UBUNTU_VERSION="18.04"
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 2.7 and tox"
    stage: test
    env: [TOXENV="py27", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.4 and tox"
    stage: test
    env: [TOXENV="py34", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.4
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.5 and tox"
    stage: test
    env: [TOXENV="py35", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.5
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.6 and tox"
    stage: test
    env: [TOXENV="py36", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
  - name: "Ubuntu Bionic (18.04) (Docker) with Python 3.7 and tox"
    stage: test
    env: [TOXENV="py37", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.7
    services:
    - docker
  - name: "MacOS with Python 2.7.10"
    stage: test
    env: [TARGET="macos-python27", PYTHONPATH="/Library/Python/2.7/site-packages/"]
    os: osx
    osx_image: xcode9.2
    language: generic
  - name: "Dockerfile"
    stage: end_to_end
    env: TARGET="dockerfile"
    os: linux
    dist: xenial
    sudo: required
    group: edge
  - name: "Jenkins on Ubuntu Bionic (18.04) (Docker) with Python 2.7"
    stage: end_to_end
    env: [TARGET="jenkins2", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 2.7
    services:
    - docker
  - name: "Jenkins on Ubuntu Bionic (18.04) (Docker) with Python 3.6"
    stage: end_to_end
    env: [TARGET="jenkins3", UBUNTU_VERSION="18.04"]
    os: linux
    dist: xenial
    sudo: required
    group: edge
    language: python
    python: 3.6
    services:
    - docker
install:
- ./config/travis/install.sh
script:
- ./config/travis/run_with_timeout.sh 30 ./config/travis/runtests.sh
